spring:
application:
name: producto-service
jpa:
hibernate:
ddl-auto: update
database-platform: org.hibernate.dialect.MySQL8Dialect
datasource:
url: jdbc:mysql://localhost:3306/service_producto?useSSL=true&serverTimezone=UTC
username: root
password: admin

server:
port: 8083

eureka:
client:
service-url:
defaultZone: http://localhost:8761/eureka